### ISSUE TITLE
incorrect day of year at midnight during DST

### ISSUE THREAD

**Issue by smhg** [commenthol/weeknumber#1]
Thanks for your work on this module!

When not testing in UTC (e.g. `TZ=Europe/Brussels npm test`), then this happens:
```javascript
dayOfYear(new Date(2018, 2, 25)) === dayOfYear(new Date(2018, 2, 26))
```
Day of year detection is one hour off because of DST.

Is this something you want to support?
I think Node runs in UTC by default, but for browsers `dayOfYear` is quite useless.

If you don't want to support it, maybe it's an idea to add `TZ=UTC` to the `npm test` script?

**Comment by commenthol** [comment]
Thanks for reporting this issue. I fixed the observed by setting an offset by two hours if the date is less then 1 hour in the morning. The functions should run both on node and browser.

**Comment by commenthol** [comment]
Just published v1.0.1

**Comment by StanlyLife** [comment]
Still not working, unix date 1663539000 is week 38 both in utc and gmt+2 (europe/oslo)

**Comment by StanlyLife** [comment]
Should note that i use moment-timezone to convert the date into gmt+2 before putting it in weekNumberYear().week and then compare them.

do the function `weekNumberYear()` do any internal date/time shifting?
