### ISSUE TITLE
Add weeksPerYear(year)

### ISSUE THREAD

**Issue by pate313373** [commenthol/weeknumber#6]
Hi,

I'd love to see a function to get the number of ISO weeks of any year.
Maybe [this](https://github.com/iamkun/dayjs/blob/dev/src/plugin/isoWeeksInYear/index.js) helps. :)

Kind regards

**Comment by commenthol** [comment]
This should help:
```js
const weeksPerYear = year => {
  let wn = weekNumber(new Date(year, 11, 31, 12))
  if (wn === 1) {
    wn = weekNumber(new Date(year, 11, 31 - 3, 12));
  }
  return wn
}
```

**Comment by pate313373** [comment]
Cool, that's pretty simple. Why didn't I think about it?

Would be nice though, if you added it as a function. 👍

**Comment by commenthol** [comment]
v1.2.0 now contains a `weeksPerYear` method
